### ISSUE TITLE
Need safety minute generator

### ISSUE THREAD

**Issue by partofthething** [whatisnuclear/website#12]
In line with our nuclear renaissance bingo generator and random reactor generator, we need a safety minute generator.

Should basically have a random button that has a summary or link to summary of various events. Probably should make them into slides, maybe with this https://revealjs.com/

Events (draft)

* [INPO 7 major historical events](https://www.nrc.gov/docs/ML1600/ML16006A288.pdf)
* [Traits of a Healthy Nuclear Safety Culture](https://www.nrc.gov/docs/ML1303/ML13031A707.pdf)
    * [Also this from WANO](https://www.wano.info/getmedia/49f169b0-a385-4cd2-a7d8-2f64b64cd8d2/WANO-PL-2013-1-Pocketbook-English.pdf.aspx)
 * [More from INPO 2004](https://www.nrc.gov/docs/ML0534/ML053410342.pdf)
 * [HTRE-3 meltdown](https://www.osti.gov/biblio/4643464-summary-report-htre-nuclear-excursion)
 * [SRE fuel melt](https://www.etec.energy.gov/Library/Main/Doc._No._2_SRE_Fuel_Element_Damage_Final_Report_1961_NAA-SR-4488_(suppl).pdf)
 * [Bicycle safety](https://www.nhtsa.gov/road-safety/bicycle-safety)
 * [Earthquake safety](https://www.cdc.gov/disasters/earthquakes/during.html)
 * [Wildfire safety](https://www.nfpa.org/Public-Education/Fire-causes-and-risks/Wildfire/Wildfire-safety-tips)
 * [Heat safety](https://www.weather.gov/safety/heat)
 * [Ladder safety](https://www.americanladderinstitute.org/page/BasicLadderSafety)
 * [Winter driving safety](https://www.nhtsa.gov/winter-driving-safety)
 * [Lawn care safety](https://www.lawyernc.com/blog/14-lawn-care-safety-tips-for-your-family/)
 * [Hurricane preparadness](https://www.cdc.gov/nceh/features/hurricanepreparedness/index.html)
 * [EMP prep](https://www.heritage.org/homeland-security/report/the-lights-go-out-survey-emp-preparedness-reveals-significant-shortfalls)
 * [Nuclear war survival skills](https://www.oism.org/nwss/)

**Comment by partofthething** [comment]
Alright we got one going here https://whatisnuclear.com/safety-minutes/ just needs to be filled in

**Comment by riddlemp** [comment]
Is this issue still open because you want enhanced functionality for the Safety Minutes? Still shooting for slide shows from the existing Safety Minutes?

**Comment by partofthething** [comment]
I can close it since we have those now. 

I did one in slide format, which I think is actually preferable for presentations: https://whatisnuclear.com/safety-minutes/1983-salem-atws.html

source: https://github.com/whatisnuclear/website/blob/master/_safetyminutes/1983-salem-atws.md?plain=1

We can try converting some over if we want. You can try one in slide mode if you want but no pressure.
