### ISSUE TITLE
Create "Helios Flight 522" Safety Minute

### ISSUE THREAD

**Issue by riddlemp** [whatisnuclear/website#19]
See attached files for Safety Minute - "Helios Airways Flight 522"

[helios-522.md](https://github.com/user-attachments/files/15519087/helios-522.md)
![helios-522-crash-site](https://github.com/whatisnuclear/website/assets/168926325/cdaa2a8e-fbda-4e07-978d-c23bcb3bb48a)

**Comment by partofthething** [comment]
Thanks man! looks great.
