### ISSUE TITLE
Create "Slips Trips and Falls"

### ISSUE THREAD

**Issue by riddlemp** [whatisnuclear/website#21]
Create Safety Minute for Slips, Trips, and Falls using the attached files. 
![slip_trip_fall](https://github.com/whatisnuclear/website/assets/168926325/e70fc3d6-3c50-422e-a920-b10a87daf71f)
[slip_trip_fall.md](https://github.com/user-attachments/files/15527101/slip_trip_fall.md)

**Comment by partofthething** [comment]
thank you sir!
