### ISSUE TITLE
Create "Administrative Controls" Safety Minute

### ISSUE THREAD

**Issue by riddlemp** [whatisnuclear/website#22]
First attempt at creating a slideshow for the safety minutes. Feedback is appreciated. Markdown file and image attached to issue. 
[admin-control.md](https://github.com/user-attachments/files/15849479/admin-control.md)
![doe-hdbk-1028-2009](https://github.com/whatisnuclear/website/assets/168926325/1a945a10-b17a-4876-b36d-793fee874139)

**Comment by partofthething** [comment]
Looks great, thanks! Online now here: https://whatisnuclear.com/safety-minutes/admin-control.html

I did a few small things:

* Got rid of all the `<br />`s: those generally goof up the view on different sized screens, in case anyone is doing safety minutes on a phone. The markdown format can conflict with HTML sometimes and the trick is to just get rid of most of the indents and it usually works how you want. 
* Added author to front page :)
* Hyperlinked the references
* that's all
